name: "packs"
# Version is the version of Draft plus the number of official builds for this
# plugin
version: "0.5.0+0"
usage: "manages packs"
description: "Help operate multiple charts in a cluster."
command: "$DRAFT_PLUGIN_DIR/draft-packs"
hooks:
  install: "$DRAFT_PLUGIN_DIR/install-binary.sh"
